### ISSUE TITLE
Support an "adjunct" node

### ISSUE THREAD

**Issue by caprica** [caprica/jquery-orgchart#15]
Useful e.g. for "Personal Assistant" type nodes.

**Comment by caprica** [comment]
Completed at 2eefbbd9da6f96ade16436d49856a1ced54526c5.

**Comment by saulofalcao** [comment]
Woult it be possible to have more than one adjunct for each node? It would be very useful for us!

**Comment by caprica** [comment]
Presumably you mean more than one attached on the same side?

I doubt it. I suspect there will be all sorts of CSS issues to get things in the right place and make sure things are the right size. It already has absolute CSS positioning and so on in there.

It might be possible, but it will take a pull-request or at least a properly styled working mock-up from someone.

**Comment by saulofalcao** [comment]
Thanks @caprica!
