### ISSUE TITLE
Possible improvements to "Stack management"

### ISSUE THREAD

**Issue by pierpaolocira** [caprica/jquery-orgchart#21]
Hi,
I think can be useful to differently manage how stacking works.

As far as I read, now there is just a "stack" level option, defining what's the last level to be rendered as a tree node (other will be stacked).

But what if user:
- needs to stack only childrend?
- needs to stack just several nodes?

To explain why I think it could be useful, image to render an organization chart with 3 simple specifications:
- each node should represent an office
- an office may contain other sub-offices
- office staff should be just flat-reported under a node (so as stacked node)

Putting stacked contents (es. staff) in a div (inside "li") doesn't properly work in Google Chrome, because links are "out" of td area and so not clickable (and, generally, divs will be rendered inside an H2 element and it's not formally correct)...

So my idea is to allow designer to declear as stacked only specific elements he needs.

I'm sure it will add an amazing flessibility to this great library.

Thanks.

**Comment by caprica** [comment]
Provide an html mockup of your idea and I'll see what can be done.

**Comment by pierpaolocira** [comment]
Hi, thanks for replying.

I didn't study generated code in depth, but results should be something like attached file.

[test_mockup_res.txt](https://github.com/caprica/jquery-orgchart/files/40079/test_mockup_res.txt)

**Comment by pierpaolocira** [comment]
Hi,
I realized that for the porpuses I wrote, another solution can be better: to provide the possibility to add a description to any node.
So I realized a customization of your code... it is based on the same behaviour used for managing adjuncts (both by JS side and by HTML side using another custom tag), so it needs for just few lines. Moreover it manages both HTML descriptions and descriptions based on lists (as should be necessary in case of company charts).

I'll open a pull request if you are interested... let me know

**Comment by caprica** [comment]
If you want to send something I'll certainly look at it. To include a contribution, I always give credit, but you must allow me to relicense any contribution as I see fit.

**Comment by pierpaolocira** [comment]
Does it mean that you may decide to close the source in future? Or just that you can provide this lib with a kind of close licence (e.g. for commercial purposes) beside an open source licence for personal (educational/non-commercial) usage?

**Comment by caprica** [comment]
It will always be open source, but someone might ask me for a commercial
licence.

**Comment by pierpaolocira** [comment]
Great, it's ok for me...
Can you just tell me what tool did you use for minify Javascript? In this way I can prepare a full-working branch (with JS, minified JS, css and one demo) and you can evaluate if it can be ok for you...

**Comment by caprica** [comment]
It's the google closure compiler if I remember correctly.

Don't worry about minifying it for now anyway, it may require changes.

**Comment by pierpaolocira** [comment]
Ok... in the next days I will do a pull request without minifying... hope it'll be considered useful.

**Comment by caprica** [comment]
Closed pending pull request or abandonment.

**Comment by pierpaolocira** [comment]
I'm opening a pull request: please, let me know about.
Sorry for delay.

**Comment by caprica** [comment]
Closing since all future work will go into the react-org-chart project instead.
