### ISSUE TITLE
Some question about this lib

### ISSUE THREAD

**Issue by x09326** [caprica/jquery-orgchart#24]
Hi, I'm going to add this lib to the https://cdnjs.com/ .
But I have some question.
Because we need package.json, I need to know which license it use.
And do you have the version tag?
We need add version to the package.json.

**Comment by caprica** [comment]
License here: https://github.com/caprica/jquery-orgchart/blob/master/jquery.orgchart.js

**Comment by x09326** [comment]
@caprica And do you have the version tag?

**Comment by caprica** [comment]
https://github.com/caprica/jquery-orgchart/releases/tag/1.0.0
