### ISSUE TITLE
Ability to save orgchart

### ISSUE THREAD

**Issue by gregoryduckworth** [caprica/jquery-orgchart#25]
It would be nice if there was an option to save the current status of the orgchart, with something like html2canvas

**Comment by caprica** [comment]
So what is to stop you doing that? Incorporate html2canvas into your own web-page, invoke it when you press a button, and there you go. Why does it need to be part of the orgchart plugin itself?

**Comment by gregoryduckworth** [comment]
Nothing is stop me doing it, just I think it would be a useful feature as it is quite a common function to want the ability to export/save the org chart. Other libraries such as [dabeng/OrgChart](https://github.com/dabeng/OrgChart) have added the functionality by popular request as well, so there is certainly a demand for it. So I think having it inbuilt into the library would be beneficial.

**Comment by caprica** [comment]
My philosophy is to assemble software from components, and have each component do one thing and do that thing well. I don't like to add dependencies and bloat unless there is a compelling reason to do so.

dabeng's philosophy, from what you say, is likely different.

In any case, I note that dabeng's implementation is based on wesnote's jOrgChart implementation (at least the key idea), which itself was directly based off my initial implementation. My point being you already have an option to use an equivalent chart with the feature you want.
