### ISSUE TITLE
Please mention the license

### ISSUE THREAD

**Issue by jeevasusej** [caprica/jquery-orgchart#27]
I didn't find any license for this plugin.

Can we use this plugin for the production version?

**Comment by caprica** [comment]
Look at the source code for the plugin. The license is right there.

**Comment by jeevasusej** [comment]
Can we use this for commercial use?

**Comment by caprica** [comment]
Please read the license to answer that question.

With this plugin, my goal in choosing the license I did was to ensure that me and my company gets proper credit for the plugin.

If you want a commercial license where you do not have to give credit to me or my company, then email me direct.
