### ISSUE TITLE
Any chances to make it responsive?

### ISSUE THREAD

**Issue by DanielZambranoC** [caprica/jquery-orgchart#29]
![image](https://user-images.githubusercontent.com/28786672/31183624-1a7566fa-a8f5-11e7-9191-483d6548ac33.png)

```
    display: inline-block;
    font-size: 1em;
    background-color: whitesmoke;
    min-width: 100%;
    margin: 0;
    border-radius: 4px;
```

**Comment by DanielZambranoC** [comment]
![image](https://user-images.githubusercontent.com/28786672/31187197-261204c8-a8ff-11e7-8352-f08093c501f0.png)

Using default styles

**Comment by caprica** [comment]
Start by defining the responsive behaviour. What should it actually do?

It's not easy.

**Comment by DanielZambranoC** [comment]
The only thing missing is to adjust the flowchart to the size of the parent element.

**Comment by DanielZambranoC** [comment]
![image](https://user-images.githubusercontent.com/28786672/31189648-d9d0d1ae-a906-11e7-9ccf-d97cbb803eee.png)

Have u tried it with lot of content?

**Comment by DanielZambranoC** [comment]
On your examples have the same issue

![image](https://user-images.githubusercontent.com/28786672/31191336-c968e18a-a90b-11e7-941c-4c5dd42f0f39.png)

You could add **table-layout:fixed;** on the default css **div.orgChart table**

But there is another problem

![image](https://user-images.githubusercontent.com/28786672/31191434-16796f3a-a90c-11e7-967b-7359e59e5115.png)

Looking for a workaround, if I got something gonna bring it here.

**Comment by caprica** [comment]
So in your view, responsive means scaling the chart down to fit it's parent container?

For me responsive probably means switching dropping content from the chart or switching from the chart to some other view entirely on small screens.

I can't imagine any small screen view of the chart that would look OK to be honest.

**Comment by caprica** [comment]
In this specific example, you would be much better off using the existing "stacking" feature to render the list of names rather than the "nodes", and then provide your own CSS if you want to render the stack differently.
